import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DataStoreProvider } from "./utils/DataStore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundColor: '#FBF3E1',
          background: 'linear-gradient(90deg, rgba(251, 243, 225, 1) 0%, rgba(249, 222, 219, 1) 21%, rgba(212, 236, 230, 1) 98%)',
        }}
      >
        <DataStoreProvider>
          {children}
        </DataStoreProvider>
      </body>
    </html>
  );
}
